def temperature():
  print ("Welcome to temperature calculator")
  print("Put the temperature in celsius degrees and y will transform it into farenhei and kelvin")
  celsius = input()
  print ("Okay")
  print ("Calculating")
  farenheit = ((float(celsius)*(9/5)+32))
  kelvin = (float(celsius)+273.15) 
  print ("Farenheit temperature is",farenheit)
  print ("Kelvin temperature is",kelvin)
  print ("Thanks for using our services")
               
temperature()

def rectangle():
  print ("Hi, welcome to rectangle calculator")
  print("What is your name?")
  name = input()
  print ("Hello,",name)
  print ("What are the messures of your rectangle?")
  print ("First give me the longest side")
  lside = input()
  print ("Great now the shortest side")
  sside = input()
  perimeter = (int(lside)+int(sside))*2
  area = int(lside)*int(sside)
  print ("Here are your results :D")
  print ("First your perimeter is",perimeter)
  print ("And your area is",area)
  print ("Was I helpful to you?")
  helpfullness = input()
  print ("Well, I don't even care JAJAJJAJAJAJAJAJJAAJJAJAJA")
  print ("Goodbye",name)
rectangle()
